import random

whalecore = [
    "SPLIT YOUR LUNGS WITH BLOOD AND THUNDER",
    "WHEN YOU SEE THE WHITE WHALE",
    "BREAK YOUR BACKS AND CRACK YOUR OARS, MEN",
    "IF YOU WISH TO PREVAIL",
    "THIS IVORY LEG IS WHAT PROPELS ME",
    "HARPOONS THRUST IN THE SKY",
    "AIM DIRECTLY FOR HIS CROOKED BROW",
    "AND LOOK HIM STRAIGHT IN THE EYE",
    "I THINK THAT SOMEONE IS TRYING TO KILL ME",
    "INFECTING MY BLOOD AND DESTROYING MY MIND",
    "NO MAN OF THE FLESH COULD EVER STOP ME",
    "THE FIGHT FOR THIS FISH IS A FIGHT TO THE DEATH",
]

def run(data, settings):
    if data['payload'] == 'whale':
        return random.choice(whalecore)
